"""Best-effort Terraform (HCL) rendering for a proposed AccountNetworkPolicy.

`--export` writes the proposed policy as JSON (a curl / REST body) and, alongside it, a Terraform
config. The `databricks_account_network_policy` resource models every nested element as a typed
**attribute** (a nested object / list of objects), not a repeated block — so the HCL uses attribute
assignment throughout: `egress = { ... }` and `allowed_internet_destinations = [ { ... } ]`, not
`egress { ... }`. The attribute names still track a newer provider schema, so the HCL remains a
*starting point to review*, but it validates + applies against current provider versions.
"""

from __future__ import annotations

import re

RESOURCE_TYPE = "databricks_account_network_policy"


def _tf_name(policy_id: str) -> str:
    """A Terraform-safe resource label derived from the policy id."""
    name = re.sub(r"[^a-zA-Z0-9_]", "_", policy_id or "").strip("_")
    if not name or not re.match(r"[a-zA-Z_]", name):
        name = f"np_{name}" if name else "network_policy"
    return name


def _scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def _lines(obj: dict, indent: int) -> list[str]:
    """Render a dict's key/values as HCL attribute assignments. The provider's network-policy schema
    is all nested attributes (objects / lists of objects), so nested structures are assigned with
    `=`: a dict becomes `key = { ... }` and a list of dicts becomes `key = [ { ... }, { ... } ]`."""
    pad = "  " * indent
    out: list[str] = []
    for key, val in obj.items():
        if val is None or (isinstance(val, (list, dict)) and not val):
            continue  # omit nulls and empties
        if isinstance(val, dict):
            out.append(f"{pad}{key} = {{")
            out += _lines(val, indent + 1)
            out.append(f"{pad}}}")
        elif isinstance(val, list) and all(isinstance(i, dict) for i in val):
            # list of objects -> an attribute assigned a list literal of object literals
            out.append(f"{pad}{key} = [")
            for i, item in enumerate(val):
                out.append(f"{pad}  {{")
                out += _lines(item, indent + 2)
                out.append(f"{pad}  }}" + ("," if i < len(val) - 1 else ""))
            out.append(f"{pad}]")
        elif isinstance(val, list):
            out.append(f"{pad}{key} = [{', '.join(_scalar(i) for i in val)}]")
        else:
            out.append(f"{pad}{key} = {_scalar(val)}")
    return out


def network_policy_hcl(policy: dict) -> str:
    """Best-effort `databricks_account_network_policy` HCL for the proposed policy dict (from
    AccountNetworkPolicy.as_dict()). account_id is dropped — the provider supplies it."""
    pid = policy.get("network_policy_id") or "network_policy"
    body = {k: v for k, v in policy.items() if k != "account_id"}
    header = [
        "# Best-effort Terraform generated by dbx-migrate-ip-acls — REVIEW before `terraform apply`.",
        f"# Targets the `{RESOURCE_TYPE}` resource; attribute/block names for account network",
        "# policies are newer and may differ by Databricks provider version.",
        f'resource "{RESOURCE_TYPE}" "{_tf_name(pid)}" {{',
    ]
    return "\n".join(header + _lines(body, 1) + ["}"]) + "\n"
